import json
from pathlib import Path

from docx import Document
from pptx import Presentation
from pptx.util import Inches
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer


def _safe_title(value: str) -> str:
    return "".join(c if c.isalnum() else "-" for c in value).strip("-")[:60] or "output"


def create_artifacts(result: dict, *, agent_type: str, output_dir: Path) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    base = _safe_title(result.get("title", agent_type))
    json_path = output_dir / f"{base}.json"
    json_path.write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8")
    paths = [json_path, _create_docx(result, output_dir / f"{base}.docx")]
    paths.append(_create_pdf(result, output_dir / f"{base}.pdf"))
    if agent_type == "teaching":
        paths.append(_create_pptx(result, output_dir / f"{base}.pptx"))
    return paths


def _create_docx(result: dict, path: Path) -> Path:
    doc = Document()
    doc.add_heading(result.get("title", "Professor AI Output"), 0)
    for key, value in result.items():
        if key == "title":
            continue
        doc.add_heading(key.replace("_", " ").title(), level=1)
        _docx_value(doc, value)
    doc.save(path)
    return path


def _docx_value(doc: Document, value) -> None:
    if isinstance(value, list):
        for item in value:
            if isinstance(item, dict):
                doc.add_paragraph(json.dumps(item, ensure_ascii=False), style="List Bullet")
            else:
                doc.add_paragraph(str(item), style="List Bullet")
    elif isinstance(value, dict):
        for key, item in value.items():
            doc.add_paragraph(f"{key.replace('_', ' ').title()}: {item}")
    else:
        doc.add_paragraph(str(value))


def _create_pdf(result: dict, path: Path) -> Path:
    styles = getSampleStyleSheet()
    story = [Paragraph(result.get("title", "Professor AI Output"), styles["Title"]), Spacer(1, 16)]
    for key, value in result.items():
        if key == "title":
            continue
        story.append(Paragraph(key.replace("_", " ").title(), styles["Heading2"]))
        rendered = json.dumps(value, ensure_ascii=False, indent=2) if not isinstance(value, str) else value
        for line in rendered.splitlines() or [""]:
            story.append(Paragraph(line.replace("&", "&amp;").replace("<", "&lt;"), styles["BodyText"]))
        story.append(Spacer(1, 10))
    SimpleDocTemplate(str(path), pagesize=A4, title=result.get("title", "")).build(story)
    return path


def _create_pptx(result: dict, path: Path) -> Path:
    deck = Presentation()
    deck.slide_width = Inches(13.333)
    deck.slide_height = Inches(7.5)
    title_slide = deck.slides.add_slide(deck.slide_layouts[0])
    title_slide.shapes.title.text = result.get("title", "Teaching Package")
    title_slide.placeholders[1].text = result.get("overview", "Generated by Professor AI")
    for section in result.get("lecture_sections", []):
        slide = deck.slides.add_slide(deck.slide_layouts[1])
        slide.shapes.title.text = section.get("title", "Lecture Section")
        frame = slide.placeholders[1].text_frame
        frame.clear()
        for index, point in enumerate(section.get("content", [])):
            paragraph = frame.paragraphs[0] if index == 0 else frame.add_paragraph()
            paragraph.text = str(point)
    for heading, values in (
        ("Learning Objectives", result.get("learning_objectives", [])),
        ("Discussion Questions", result.get("discussion_questions", [])),
        ("Viva Questions", result.get("viva_questions", [])),
    ):
        slide = deck.slides.add_slide(deck.slide_layouts[1])
        slide.shapes.title.text = heading
        frame = slide.placeholders[1].text_frame
        frame.clear()
        for index, value in enumerate(values[:8]):
            paragraph = frame.paragraphs[0] if index == 0 else frame.add_paragraph()
            paragraph.text = str(value)
    deck.save(path)
    return path
