import json
from html import escape
from pathlib import Path
from typing import Any

from docx import Document
from pptx import Presentation
from pptx.util import Inches
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer


def _plain_text(value: Any, fallback: str = "") -> str:
    """Convert structured model values into text accepted by document libraries."""
    if value is None:
        return fallback
    if isinstance(value, str):
        return value
    if isinstance(value, dict):
        for preferred_key in ("title", "text", "value", "name", "summary", "description"):
            preferred = value.get(preferred_key)
            if preferred is not None:
                return _plain_text(preferred, fallback)
        return json.dumps(value, ensure_ascii=False, default=str)
    if isinstance(value, (list, tuple)):
        return "\n".join(_plain_text(item) for item in value)
    return str(value)


def _safe_title(value: Any) -> str:
    text = _plain_text(value, "output")
    return "".join(c if c.isalnum() else "-" for c in text).strip("-")[:60] or "output"


def create_artifacts(result: dict, *, agent_type: str, output_dir: Path) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    base = _safe_title(result.get("title", agent_type))
    json_path = output_dir / f"{base}.json"
    json_path.write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8")
    paths = [json_path, _create_docx(result, output_dir / f"{base}.docx")]
    paths.append(_create_pdf(result, output_dir / f"{base}.pdf"))
    if agent_type == "teaching":
        paths.append(_create_pptx(result, output_dir / f"{base}.pptx"))
    return paths


def _create_docx(result: dict, path: Path) -> Path:
    doc = Document()
    doc.add_heading(_plain_text(result.get("title"), "Professor AI Output"), 0)
    for key, value in result.items():
        if key == "title":
            continue
        doc.add_heading(key.replace("_", " ").title(), level=1)
        _docx_value(doc, value)
    doc.save(path)
    return path


def _docx_value(doc: Document, value) -> None:
    if isinstance(value, list):
        for item in value:
            if isinstance(item, dict):
                doc.add_paragraph(json.dumps(item, ensure_ascii=False), style="List Bullet")
            else:
                doc.add_paragraph(str(item), style="List Bullet")
    elif isinstance(value, dict):
        for key, item in value.items():
            doc.add_paragraph(f"{key.replace('_', ' ').title()}: {item}")
    else:
        doc.add_paragraph(str(value))


def _create_pdf(result: dict, path: Path) -> Path:
    styles = getSampleStyleSheet()
    title = _plain_text(result.get("title"), "Professor AI Output")
    story = [Paragraph(escape(title), styles["Title"]), Spacer(1, 16)]
    for key, value in result.items():
        if key == "title":
            continue
        story.append(Paragraph(key.replace("_", " ").title(), styles["Heading2"]))
        rendered = _plain_text(value)
        for line in rendered.splitlines() or [""]:
            story.append(Paragraph(escape(line), styles["BodyText"]))
        story.append(Spacer(1, 10))
    SimpleDocTemplate(str(path), pagesize=A4, title=title).build(story)
    return path


def _create_pptx(result: dict, path: Path) -> Path:
    deck = Presentation()
    deck.slide_width = Inches(13.333)
    deck.slide_height = Inches(7.5)
    title_slide = deck.slides.add_slide(deck.slide_layouts[0])
    title_slide.shapes.title.text = _plain_text(result.get("title"), "Teaching Package")
    title_slide.placeholders[1].text = _plain_text(
        result.get("overview"), "Generated by Professor AI"
    )
    for section in result.get("lecture_sections", []):
        if not isinstance(section, dict):
            section = {"title": "Lecture Section", "content": [section]}
        slide = deck.slides.add_slide(deck.slide_layouts[1])
        slide.shapes.title.text = _plain_text(section.get("title"), "Lecture Section")
        frame = slide.placeholders[1].text_frame
        frame.clear()
        content = section.get("content", [])
        if not isinstance(content, list):
            content = [content]
        for index, point in enumerate(content):
            paragraph = frame.paragraphs[0] if index == 0 else frame.add_paragraph()
            paragraph.text = _plain_text(point)
    for heading, values in (
        ("Learning Objectives", result.get("learning_objectives", [])),
        ("Discussion Questions", result.get("discussion_questions", [])),
        ("Viva Questions", result.get("viva_questions", [])),
    ):
        slide = deck.slides.add_slide(deck.slide_layouts[1])
        slide.shapes.title.text = heading
        frame = slide.placeholders[1].text_frame
        frame.clear()
        if not isinstance(values, list):
            values = [values]
        for index, value in enumerate(values[:8]):
            paragraph = frame.paragraphs[0] if index == 0 else frame.add_paragraph()
            paragraph.text = _plain_text(value)
    deck.save(path)
    return path
